[project]
name = "django-shareserver"
version = "0.1.2"
description = "Simple file sharing webpage for personal use"
requires-python = ">=3.13"
dependencies = [
    "django>=5",
    "django-celery-beat>=2",
    "dotenv>=0.9",
    "granian[pname]>=2",
    "whitenoise",
]
